[tool.black]
skip-string-normalization = true  # Optional: Prevent string quotes normalization if desired

[tool.ruff]
ignore = ["E501", "ANN", "D107"]  # E501: Ignore line length errors globally; ANN: Ignore untyped annotation warnings; D107: Ignore missing docstring in __init__
exclude = ["tests/"]  # Exclude specific directories
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "C90", # mccabe
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "S",   # flake8-bandit
    "A",   # flake8-builtins
]

[tool.ruff.lint]
exclude = ["tests/"]

[tool.ruff.lint.pydocstyle]
convention = "google"  # Enforce Google-style docstrings

[tool.ruff.lint.mccabe]
max-complexity = 10  # Limit cyclomatic complexity

[tool.pytest.ini_options]
testpaths = ["tests"]  # Define test directory
pythonpath = ["src"]   # Add src directory to Python path

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true  # Avoid errors on missing imports
disallow_untyped_defs = true   # Enforce typing in non-test code
strict_optional = true         # Enable strict optional checking

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false  # Allow untyped function definitions in test files
check_untyped_defs = false     # Disable checks for untyped function definitions
ignore_errors = true           # Ignore all errors in test modules
disable_error_code = ["no-untyped-def"]  # Explicitly disable no-untyped-def errors in tests
