# Processing settings
processing:
  max_batch_size: 100
  batch_timeout: 300
  max_workers: null  # Uses CPU count * 2 if null
  retry_attempts: 3
  retry_delay: 1

# Vale runner settings  
vale_runner:
  timeout: 30
  min_alert_level: "suggestion"
  max_issues: 100
  ignore_patterns:
    - "^\\s*$"
    - "^#.*$"

# LLM settings
llm:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 500
  timeout: 60

# Prompt settings
prompts:
  max_length: 2000
  cache_size: 32
  template_dir: "prompts/"
